name: Formatting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  prettier:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env: 
          Name: A7med3bdulBaset

      - name: Run Prettier
        run: npx prettier --write .

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.name "A7med3bdulBaset"
          git config --local user.email 'A7med3bdulBaset@users.noreply.github.com
          git add .
          git commit -m "[Bot]: Format code with Prettier"
          git push

