name: Formatting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  prettier:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Prettier
        run: npx prettier --write .

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Ahmed Abdeblbaset'
          git config --global user.email 'A7med3bdulBaset@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b formatting-${{ github.event.pull_request.number }}
          git commit -am "Automated changes"
          git push origin formatting-${{ github.event.pull_request.number }}