name: Formatting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions: read-all

jobs:
  prettier:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env: 
          Name: A7med3bdulBaset

      - name: Run Prettier
        run: npx prettier --write .

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am --no-edit 
        
      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
